apiVersion: v1
kind: Service
metadata:
  name: {{ include "commandhunt.fullname" . }}-cassandra
  labels:
    {{- include "commandhunt.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
  selector:
    {{- include "commandhunt.selectorLabels" . | nindent 4 }}-cassandra
