apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "commandhunt.fullname" . }}-elasticsearch
  labels:
    {{- include "commandhunt.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "commandhunt.fullname" . }}-elasticsearch
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "commandhunt.selectorLabels" . | nindent 6 }}-elasticsearch
  template:
    metadata:
      labels:
        {{- include "commandhunt.selectorLabels" . | nindent 8 }}-elasticsearch
    spec:
      containers:
        - name: {{ .Chart.Name }}-elasticsearch
          image: {{ .Values.statefulset.elasticsearch.image }}
          resources:
            requests:
              cpu: 500m
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: cluster.name
              value: es-cluster
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "{{ .Chart.Name }}-elasticsearch-0.{{ .Chart.Name }}-elasticsearch,{{ .Chart.Name }}-elasticsearch-1.{{ .Chart.Name }}-elasticsearch"
            - name: cluster.initial_master_nodes
              value: "{{ .Chart.Name }}-elasticsearch-0,{{ .Chart.Name }}-elasticsearch-1"
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
  volumeClaimTemplates:
    - metadata:
        name: es-data
        labels:
          {{- include "commandhunt.selectorLabels" . | nindent 10 }}-elasticsearch
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storageClassName }}
        resources:
          requests:
            storage: 1Gi