apiVersion: v1
kind: Service
metadata:
  name: {{ include "commandhunt.fullname" . }}-postgres
  labels:
    {{- include "commandhunt.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 5432
  selector:
    {{- include "commandhunt.selectorLabels" . | nindent 4 }}-postgres
