# This property file values will override values from application.yml file when using dev profile

app:
  jwt:
    secret: test
  oauth2:
    authorizedRedirectUris: http://localhost:3000/login
spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
  h2:
    console:
      # http://localhost:8080/h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none