name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Note: GitHub does not pass secrets(for security reasons) to PR workflows created with forked repos
    # So do not use any actions that require secrets
    # Tee GITHUB_TOKEN secret is allowed with readonly access for PR workflows created with forked repos

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
      # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
      MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
      # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used when running from the command line.
      MAVEN_CLI_OPTS: "--update-snapshots --batch-mode --errors --fail-at-end --show-version"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # Location for the settings.xml file

      - name: Cache SonarCloud Packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Cache NPM Packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Build with Maven
        run: mvn $MAVEN_CLI_OPTS verify

      - name: Publish Unit Test Results # Shown on actions or pull requests views on github
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: backend/target/surefire-reports/TEST-*.xml

      - name: Codecov
        uses: codecov/codecov-action@v1.5.0